# Since firstly we are making the kind cluster where we can make the kubernetes cluster inside the 
# Docker 
kind : Cluster
apiVersion : kind.x-k8s.io/v1alpha4
# We are now going to create the nodes for our cluster 
nodes : 
- role : control-plane
  image: kindest/node:v1.31.2
- role : worker
  image: kindest/node:v1.31.2
- role : worker
  image: kindest/node:v1.31.2
- role : worker
  image: kindest/node:v1.31.2
  extraPortMappings :
  -  containerPort : 80
     hostPort : 80
     protocol : TCP 
  -  containerPort : 443

# For creation of this cluster we need a command 
##
# kind create cluster --name=first-cluster --config=cluster_config.yaml
##
## Output be like something 
# Creating cluster "first-cluster" ...
# â€¢ Ensuring node image (kindest/node:v1.31.2) ğŸ–¼  ...
# âœ“ Ensuring node image (kindest/node:v1.31.2) ğŸ–¼
# â€¢ Preparing nodes ğŸ“¦ ğŸ“¦ ğŸ“¦ ğŸ“¦   ...
# âœ“ Preparing nodes ğŸ“¦ ğŸ“¦ ğŸ“¦ ğŸ“¦ 
# â€¢ Writing configuration ğŸ“œ  ...
# âœ“ Writing configuration ğŸ“œ
# â€¢ Starting control-plane ğŸ•¹ï¸  ...
# âœ“ Starting control-plane ğŸ•¹ï¸
# â€¢ Installing CNI ğŸ”Œ  ...
# âœ“ Installing CNI ğŸ”Œ
# â€¢ Installing StorageClass ğŸ’¾  ...
# âœ“ Installing StorageClass ğŸ’¾
# â€¢ Joining worker nodes ğŸšœ  ...
# âœ“ Joining worker nodes ğŸšœ
# Set kubectl context to "kind-first-cluster"


# Command to check cluster info 
# kubectl cluster-info --context kind-first-cluster
