# Since firstly we are making the kind cluster where we can make the kubernetes cluster inside the 
# Docker 
kind : Cluster
apiVersion : kind.x-k8s.io/v1alpha4
# We are now going to create the nodes for our cluster 
nodes : 
- role : control-plane
  image: kindest/node:v1.31.2
- role : worker
  image: kindest/node:v1.31.2
- role : worker
  image: kindest/node:v1.31.2
- role : worker
  image: kindest/node:v1.31.2
  extraPortMappings :
  -  containerPort : 80
     hostPort : 80
     protocol : TCP 
  -  containerPort : 443

# For creation of this cluster we need a command 
##
# kind create cluster --name=first_cluster --config=cluster_config.yaml
##